Repository Braendli98/Abgabe2, pull requests merged in 2025-01, with the labels that each got.

#16 feat: add bookcovers
  public/covers/978-0-007-09732-6.jpg
  public/covers/978-0-201-63361-0.jpg
  public/covers/978-3-540-43081-0.jpg
  public/covers/978-3-824-40481-0.jpg
  public/covers/978-3-827-31552-6.jpg
  public/covers/978-3-897-22583-1.jpg
  src/components/BookCard.tsx
Labels: enhancement

#10 add: filterfunction_searchinOverview
  src/components/Header.tsx
  src/components/Overview.tsx
Labels: enhancement

#13 feat: header ui anpassen
  src/assets/hka.png
  src/components/Header.tsx
Labels: enhancement

#14 Feature/md/login UI 2
  src/components/Login.tsx
Labels: enhancement

#12 Feature/ab/addbook
  src/App.tsx
  src/components/AddBook.tsx
  src/components/AddCard.tsx
  src/components/Details.tsx
  src/components/Overview.tsx
Labels: enhancement

#9 feat: add error handling
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Details.tsx
  src/components/ErrorComponent.tsx
  src/components/Login.tsx
  src/components/LoginAlert.tsx
  src/components/UserMenu.tsx
  src/components/ui/alert.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/delete-validation.ts
  src/lib/login-validation.ts
  src/types/details.ts
  src/types/login.ts
Labels: enhancement

#15 feat: add some basic cypress tests, add basic github workflow
  .github/workflows/docs.yml
  .github/workflows/workflow.yml
  cypress.config.js
  cypress/e2e/login.spec.cy.ts
  cypress/e2e/overview.spec.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  docs/projekthandbuch.adoc
  docs/uml/state.plantuml
  package-lock.json
  package.json
  scripts/asciidoctor.js
  src/App.tsx
  src/components/AddBook.tsx
  src/components/AddCard.tsx
  src/components/BookCard.tsx
  src/components/Context.tsx
  src/components/Details.tsx
  src/components/ErrorComponent.tsx
  src/components/Header.tsx
  src/components/Login.tsx
  src/components/LoginAlert.tsx
  src/components/Overview.tsx
  src/components/UserMenu.tsx
  src/components/ui/alert.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/delete-validation.ts
  src/lib/login-validation.ts
  src/types/context.ts
  src/types/details.ts
  src/types/login.ts
Labels: enhancement

#17 feat: reorganize react components, add toasts to BookAdd, extract cover as BookCover
  cypress/e2e/login.spec.cy.ts
  public/covers/image-off.svg
  src/App.tsx
  src/components/add/AddBook.tsx
  src/components/common/BookCover.tsx
  src/components/common/Breadcrumbs.tsx
  src/components/common/ContentLayout.tsx
  src/components/common/Context.tsx
  src/components/details/Details.tsx
  src/components/error-handling/ErrorComponent.tsx
  src/components/header/Header.tsx
  src/components/header/UserMenu.tsx
  src/components/login/Login.tsx
  src/components/login/LoginAlert.tsx
  src/components/overview/AddCard.tsx
  src/components/overview/BookCard.tsx
  src/components/overview/Overview.tsx
  src/components/shadcn-ui/alert.tsx
  src/components/shadcn-ui/breadcrumb.tsx
  src/components/shadcn-ui/button.tsx
  src/components/shadcn-ui/card.tsx
  src/components/shadcn-ui/dropdown-menu.tsx
  src/components/shadcn-ui/input.tsx
  src/components/shadcn-ui/label.tsx
  src/components/shadcn-ui/toast.tsx
  src/components/shadcn-ui/toaster.tsx
  src/hooks/use-toast.ts
  src/lib/add-validation.ts
  src/lib/breadcrumb-utils.ts
  src/lib/login-validation.ts
  src/types/breadcrumb.ts
Labels: enhancement

#19 fix: fix eslint and react warnings
  src/components/add/AddBook.tsx
  src/components/common/Breadcrumbs.tsx
  src/components/common/Context.tsx
  src/components/details/Details.tsx
  src/components/header/Header.tsx
  src/components/login/Login.tsx
  src/components/overview/Overview.tsx
  src/components/shadcn-ui/button.tsx
  src/components/shadcn-ui/toast.tsx
  src/hooks/use-context.ts
Labels: bug

#26 feat: better Readme
  README.md
  docs/projekthandbuch.adoc
  src/components/header/Header.tsx
Labels: documentation
